# Run this workflow MANUALLY to get a Unity license for CI
# Go to Actions tab → "Request Unity License" → "Run workflow"
# Download the .alf artifact, then:
# 1. Go to https://license.unity3d.com/manual
# 2. Upload the .alf file
# 3. Copy the returned .ulf contents
# 4. Add as UNITY_LICENSE secret in repo Settings → Secrets

name: Request Unity License

on:
  workflow_dispatch:

jobs:
  activation:
    runs-on: ubuntu-latest
    steps:
      - name: Request activation file
        id: license
        uses: game-ci/unity-request-activation-file@v2

      - uses: actions/upload-artifact@v4
        with:
          name: UnityLicenseFile
          path: ${{ steps.license.outputs.filePath }}
